name: Deploy to gh-pages
on:
  push:
    branches: [ "main" ]  # Se activa con cambios en main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiso para push a gh-pages

    steps:
      - uses: actions/checkout@v4

      # Filtra archivos (personaliza esta lista)
      - name: Filter files
        run: |
          rm -rf .github/ README.md SECURITY.md LICENSE.md
          mkdir -p public
          cp -r index.html css/ js/ public/  # Copia SOLO lo necesario

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # ¡Nuevo! Usa una carpeta filtrada
          publish_branch: gh-pages
          keep_files: false  # Limpia la rama gh-pages completamente
          force_orphan: true  # Elimina el historial previo (opcional)
